version: "3.5"

volumes:
  install-home: {}
  sum-home: {}
  audit: {}

networks:
    n1:
      external: false
services:
  apigw-1007-2:
    build:
      context: ../../../Framework/GenericUbiMinimalSandbox/build
      args:
        - __suif_audit_base_dir=${SUIF_AUDIT_BASE_DIR}
        - __suif_home=${SUIF_HOME}
        - __suif_install_image_file=${SUIF_INSTALL_IMAGE_FILE}
        - __suif_install_install_dir=${SUIF_INSTALL_INSTALL_DIR}
        - __suif_install_installer_bin_mount_point=${SUIF_INSTALL_INSTALLER_BIN_MOUNT_POINT}
        - __suif_local_scripts_home=${SUIF_TEST_LOCAL_SCRIPTS_DIR}
        - __suif_patch_fixes_image_file=${SUIF_PATCH_FIXES_IMAGE_FILE}
        - __suif_patch_sum_bootstrap_bin_mount_point=${SUIF_PATCH_SUM_BOOTSTRAP_BIN_MOUNT_POINT}
        - __suif_sag_user_grp_id=1804
        - __suif_sag_user_name=sag
        - __suif_sum_home=${SUIF_SUM_HOME}
        - __suif_work_dir=${SUIF_WORK_DIR}
    image: api-gw-1007-default-ubi-test-2
    container_name: api-gw-1007-default-test-2
    hostname: api-gw-1007-default-test-2
    ulimits:
      nproc: 4096
      nofile: 65536
    volumes:
      # the following must match the Dokerfile folders, otherwise permissions on FS will not work
      - install-home:${SUIF_INSTALL_INSTALL_DIR}
      - sum-home:${SUIF_SUM_HOME}
      - audit:${SUIF_AUDIT_BASE_DIR}
      - ./scripts:${SUIF_TEST_LOCAL_SCRIPTS_DIR}
      # These must be provided, they are prerequisites
      - ${H_API_GW_LICENSE_FILE}:${SUIF_SETUP_TEMPLATE_YAI_LICENSE_FILE}
      - ${H_SUIF_FIXES_IMAGE_FILE}:${SUIF_PATCH_FIXES_IMAGE_FILE}
      - ${H_SUIF_PRODUCTS_IMAGE_FILE}:${SUIF_INSTALL_IMAGE_FILE}
      - ${H_SUIF_SUM_BOOTSTRAP_BIN}:${SUIF_PATCH_SUM_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_SUIF_INSTALLER_BIN}:${SUIF_INSTALL_INSTALLER_BIN_MOUNT_POINT}
      - ../../../../:${SUIF_HOME}
    environment:
      # we declare SUIF_HOME because we mount it here
      - SUIF_HOME
      # setupFunctions prerequisites map, declared here because provided by host
      - SUIF_INSTALL_INSTALLER_BIN
      - SUIF_INSTALL_IMAGE_FILE
      - SUIF_PATCH_SUM_BOOTSTRAP_BIN
      - SUIF_PATCH_FIXES_IMAGE_FILE
      # declare install dir and SUM dir because they are mounted here
      # setup template specifics - license provided by host
      - SUIF_SETUP_TEMPLATE_YAI_LICENSE_FILE
      - SUIF_PATCH_AVAILABLE
      - SUIF_ONLINE_MODE
      - SUIF_SDC_ONLINE_MODE
      - SUIF_DEBUG_ON
      - SUIF_APIGW_ADMINISTRATOR_PASSWORD=manage1
      - SUIF_APIGW_OLD_ADMINISTRATOR_PASSWORD=manage
      - SUIF_APIGW_NEW_ADMINISTRATOR_PASSWORD=manage1
      - SUIF_APIGW_LB_JSON_FILE=${SUIF_TEST_LOCAL_SCRIPTS_DIR}/config/lb.json
      - SUIF_APIGW_SETTINGS_JSON_FILE=${SUIF_TEST_LOCAL_SCRIPTS_DIR}/config/putSettings.json
      - http.cors.allow-origin=/https?:\/\/(localhost|host.docker.internal)(:[0-9]+)?/
      # host related, but still needed
      - H_SUIF_PORT_PREFIX
    ports:
      - "${H_SUIF_PORT_PREFIX}20:9240"
      - "${H_SUIF_PORT_PREFIX}73:9073"
      - "${H_SUIF_PORT_PREFIX}72:9072"
      - "${H_SUIF_PORT_PREFIX}55:5555"
    networks:
      n1:
        aliases:
          - apigw-server
    entrypoint: ${SUIF_TEST_LOCAL_SCRIPTS_DIR}/containerEntrypoint.sh
  elasticvue:
    image: cars10/elasticvue
    ports:
      - "${H_SUIF_PORT_PREFIX}80:8080"
    networks:
      n1:
        aliases:
          - elasticvue
