version: '3.8'
volumes:
  db-data: {}
  ats-audit: {}
  ats-sum-home: {}
  ats-wm-ats-home: {}
  ats-wm-dbc-home: {}
  ats-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
networks:
    n1:
      external: false
services:
  db:
    image: ${SUIF_TEST_POSTGRESQL_IMAGE}
    restart: always
    environment:
      - POSTGRES_USER=${SUIF_DBSERVER_USER_NAME}
      - POSTGRES_PASSWORD=${SUIF_DBSERVER_PASSWORD}
    networks:
      n1:
        aliases:
          - ${SUIF_DBSERVER_HOSTNAME}
    # comment out ports, supposed to be used internally only
    #ports:
    #  - "${SUIF_TEST_PORT_PREFIX}32:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  adminer:
    image: adminer
    hostname: adminer
    networks:
      - n1
    ports:
      - "${SUIF_TEST_PORT_PREFIX}80:8080"
    depends_on:
      db:
        condition: service_healthy
  ats:
    build:
      context: ./build-ats
      args:
        - SRC_IMAGE
        #-SUIF_TEST_GPG_KEYS_FILE_1
        - SUIF_INSTALL_INSTALL_DIR_ATS
        - SUIF_INSTALL_INSTALL_DIR_DBC
        - SUIF_SUM_HOME
        - SUIF_USER_HOME
        - SUIF_LOCAL_SCRIPTS_HOME
        - SUIF_AUDIT_BASE_DIR
        - SUIF_HOME
    hostname: ${SUIF_INSTALL_DECLARED_HOSTNAME}
    volumes:
      - ats-temp:/tmp/
      - ats-audit:${SUIF_AUDIT_BASE_DIR}
      - ats-sum-home:${SUIF_SUM_HOME}
      - ats-wm-ats-home:${SUIF_INSTALL_INSTALL_DIR_ATS}
      - ats-wm-dbc-home:${SUIF_INSTALL_INSTALL_DIR_DBC}
      - ./scripts/:${SUIF_LOCAL_SCRIPTS_HOME}
      - ../../../../:${SUIF_HOME}
    environment:
      # our test harness context
      - SUIF_ONLINE_MODE
      - SUIF_DEBUG_ON
    networks:
      - n1
    ports:
      - "${SUIF_TEST_PORT_PREFIX}55:${SUIF_WMSCRIPT_IntegrationServerPort}"
      - "${SUIF_TEST_PORT_PREFIX}53:${SUIF_WMSCRIPT_IntegrationServersecurePort}"
      - "${SUIF_TEST_PORT_PREFIX}50:${SUIF_WMSCRIPT_mftGWPortField}"
      - "${SUIF_TEST_PORT_PREFIX}90:9100"
      - "${SUIF_TEST_PORT_PREFIX}92:9102"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ${SUIF_LOCAL_SCRIPTS_HOME}/containerEntrypoint.sh
