version: "3.5"

volumes:
  lean1011-test1-install-home: {}
  lean1011-test1-runs: {}
  lean1011-test1-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  lean1011-test1:
    build: 
      context: ./build
      args:
        - SUIF_INSTALL_INSTALL_DIR=${SUIF_INSTALL_INSTALL_DIR}
        - SUIF_AUDIT_BASE_DIR=${SUIF_AUDIT_BASE_DIR}
        - SUIF_INSTALL_INSTALLER_BIN=${SUIF_INSTALL_INSTALLER_BIN}
        - SUIF_INSTALL_IMAGE_FILE=${SUIF_INSTALL_IMAGE_FILE}
        - SUIF_SAG_USER_NAME=${SUIF_SAG_USER_NAME}
        - SUIF_LOCAL_SCRIPTS_HOME=${SUIF_LOCAL_SCRIPTS_HOME}
    image: lean1011-test1
    container_name: lean1011-test1-1
    hostname: lean1011-test1-1
    volumes:
      - lean1011-test1-temp:/tmp/
      # the following must match the Dokerfile folders, otherwise permissions on FS will not work
      - lean1011-test1-install-home:${SUIF_INSTALL_INSTALL_DIR}/
      - lean1011-test1-runs:${SUIF_AUDIT_BASE_DIR}/
      - ./scripts/:${SUIF_LOCAL_SCRIPTS_HOME}/
      # These must be provided, they are prerequisites
      - ${H_MSR_LICENSE_FILE}:${SUIF_SETUP_TEMPLATE_MSR_LICENSE_FILE}
      - ${H_SUIF_PRODUCTS_IMAGE_FILE}:${SUIF_INSTALL_IMAGE_FILE}
      - ${H_SUIF_INSTALLER_BIN}:${SUIF_INSTALL_INSTALLER_BIN}
      - ../../../../:${SUIF_HOME}/
    environment:
      - SUIF_HOME
      - SUIF_AUDIT_BASE_DIR
      - SUIF_INSTALL_INSTALLER_BIN
      - SUIF_INSTALL_IMAGE_FILE
      - SUIF_PATCH_AVAILABLE
      - SUIF_INSTALL_INSTALL_DIR
      - SUIF_SETUP_TEMPLATE_MSR_LICENSE_FILE
      - SUIF_INSTALL_TIME_ADMIN_PASSWORD
      - SUIF_LOCAL_SCRIPTS_HOME
      - SUIF_ONLINE_MODE
      - SUIF_DEBUG_ON
    ports:
      - "${H_SUIF_PORT_PREFIX}55:5555"
      - "${H_SUIF_PORT_PREFIX}53:5553"
      - "${H_SUIF_PORT_PREFIX}99:9999"
    entrypoint: ${SUIF_LOCAL_SCRIPTS_HOME}/containerEntrypoint.sh
