version: "3.5"

volumes:
  install-home: {}
  sum-home: {}
  suif-cache: {}
  audit: {}

networks:
    n1:
      external: false
services:
  apigw-l-1:
    build:
      context: ../../../Framework/GenericUbiMinimalWithToolsSandbox/build
      args:
        - __suif_audit_base_dir=${SUIF_AUDIT_BASE_DIR}
        - __suif_home=${SUIF_CACHE_HOME}
        - __suif_install_image_file=${SUIF_INSTALL_IMAGE_FILE}
        - __suif_install_install_dir=${SUIF_INSTALL_INSTALL_DIR}
        - __suif_install_installer_bin_mount_point=${SUIF_INSTALL_INSTALLER_BIN_MOUNT_POINT}
        - __suif_local_scripts_home=${SUIF_TEST_LOCAL_SCRIPTS_DIR}
        - __suif_patch_fixes_image_file=${SUIF_PATCH_FIXES_IMAGE_FILE}
        - __suif_patch_sum_bootstrap_bin_mount_point=${SUIF_PATCH_SUM_BOOTSTRAP_BIN_MOUNT_POINT}
        - __suif_sag_user_grp_id=1804
        - __suif_sag_user_name=sag
        - __suif_sum_home=${SUIF_SUM_HOME}
        - __suif_work_dir=${SUIF_WORK_DIR}
    image: api-gw-1015-landscape-1-t-1
    container_name: api-gw-1015-landscape-1-t-1
    hostname: api-gw-1015-landscape-1-t-1
    mem_reservation: 512m
    mem_limit: 5g
    cpus: 4
    ulimits:
      nproc: 4096
      nofile: 65536
    volumes:
      # the following must match the Dokerfile folders, otherwise permissions on FS will not work
      - install-home:${SUIF_INSTALL_INSTALL_DIR}
      - sum-home:${SUIF_SUM_HOME}
      - audit:${SUIF_AUDIT_BASE_DIR}
      - suif-cache:${SUIF_CACHE_HOME}
      - ./scripts/ApiGateway:${SUIF_TEST_LOCAL_SCRIPTS_DIR}
      # These must be provided, they are prerequisites
      - ${H_API_GW_LICENSE_FILE}:${SUIF_SETUP_TEMPLATE_YAI_LICENSE_FILE}
      - ${H_SUIF_FIXES_IMAGE_FILE}:${SUIF_PATCH_FIXES_IMAGE_FILE}
      - ${H_SUIF_PRODUCTS_IMAGE_FILE}:${SUIF_INSTALL_IMAGE_FILE}
      - ${H_SUIF_SUM_BOOTSTRAP_BIN}:${SUIF_PATCH_SUM_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_SUIF_INSTALLER_BIN}:${SUIF_INSTALL_INSTALLER_BIN_MOUNT_POINT}
    environment:
      # we declare SUIF_CACHE_HOME instead of SUIF_HOME because we are working online and mount it here
      - SUIF_CACHE_HOME
      # setupFunctions prerequisites map, declared here because provided by host
      - SUIF_INSTALL_INSTALLER_BIN
      - SUIF_INSTALL_IMAGE_FILE
      - SUIF_PATCH_SUM_BOOTSTRAP_BIN
      - SUIF_PATCH_FIXES_IMAGE_FILE
      # declare install dir and SUM dir because they are mounted here
      # setup template specifics - license provided by host
      - SUIF_SETUP_TEMPLATE_YAI_LICENSE_FILE
      - SUIF_PATCH_AVAILABLE
      - SUIF_ONLINE_MODE
      - SUIF_SDC_ONLINE_MODE
      - SUIF_DEBUG_ON
      # host related, but still needed
      - H_SUIF_PORT_PREFIX
      - JAVA_MIN_MEM=512m
      - JAVA_MAX_MEM=1536m
    ports:
      - "${H_SUIF_PORT_PREFIX}20:9240"
      - "${H_SUIF_PORT_PREFIX}73:9073"
      - "${H_SUIF_PORT_PREFIX}72:9072"
      - "${H_SUIF_PORT_PREFIX}55:5555"
    networks:
      n1:
        aliases:
          - apigw-server
    entrypoint: ${SUIF_TEST_LOCAL_SCRIPTS_DIR}/containerEntrypoint.sh
  elasticvue:
    image: cars10/elasticvue
    ports:
      - "${H_SUIF_PORT_PREFIX}80:8080"
    cpus: 1
    mem_reservation: 100m
    mem_limit: 256m
    networks:
      n1:
        aliases:
          - elasticvue
  mock-server:
    image: ${SUIF_TEST_MOCK_SERVER_IMAGE}
    ports:
      - ${H_SUIF_PORT_PREFIX}05:5555
    volumes:
      - ${H_MSR_LICENSE_FILE}:/tmp/license.xml
      - ./config/mock-server/application.properties:/tmp/application.properties
      - ${SAG_SERVICE_MOCKUP_PACKAGE_HOME}:${SUIF_TEST_MOCK_SERVER_GUEST_IS_HOME}/packages/SagServiceMockup
    mem_reservation: 100m
    mem_limit: 370m
    container_name: mock-server
    hostname: mock-server
    cpus: 1
    environment:
      - SAG_IS_LICENSE_FILE=/tmp/license.xml
      - SAG_IS_CONFIG_PROPERTIES=/tmp/application.properties
      - JAVA_MIN_MEM=256m
      - JAVA_MAX_MEM=256m
      - SUIF_TEST_MOCK_SERVER_ADMIN_PASSWORD
      - SAG_SERVICE_MOCKUP_USER_NAME
      - SAG_SERVICE_MOCKUP_USER_PASS
    networks:
      n1:
        aliases:
          - mock-server
  test-client:
    image: ${SUIF_TEST_CLIENT_SERVER_IMAGE}
    ports:
      - ${H_SUIF_PORT_PREFIX}15:5555
    volumes:
      - ${H_MSR_LICENSE_FILE}:/tmp/license.xml
      - ./config/test-client/application.properties:/tmp/application.properties
      # dependency 
      - ${WX_IS_TEST_TOOLS_PACKAGE_HOME}:${SUIF_TEST_MOCK_SERVER_GUEST_IS_HOME}/packages/WxIsTestTools
      # our test code
      - ./code/isPackages/ApiGwBaseTests:${SUIF_TEST_MOCK_SERVER_GUEST_IS_HOME}/packages/ApiGwBaseTests
    mem_reservation: 100m
    mem_limit: 370m
    container_name: test-client
    hostname: test-client
    cpus: 1
    environment:
      - SAG_IS_LICENSE_FILE=/tmp/license.xml
      - SAG_IS_CONFIG_PROPERTIES=/tmp/application.properties
      - JAVA_MIN_MEM=256m
      - JAVA_MAX_MEM=256m
      - SUIF_TEST_CLIENT_SERVER_ADMIN_PASSWORD
    networks:
      n1:
        aliases:
          - test-client