version: "3.8"

volumes:
  sqlserver1-data: {}
  mftserver1-install-home: {}
  mftserver1-sum-home: {}
  mftserver1-runs: {}
  mftserver1-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
networks:
  n1:
    external: false
services:
  sql-server1:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: test-sql-server-1-1
    hostname: sql-server1
    volumes:
      - sqlserver1-data:/var/opt/mssql
    networks:
      n1:
        aliases:
          - sql-server1
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${H_SQLSERVER_SA_PASSWORD}
  adminer:
    image: adminer
    container_name: test-sql-server-1-adminer
    hostname: adminer
    networks:
      - n1
    depends_on:
      - "sql-server1"
    ports:
      - "${H_SUIF_PORT_PREFIX}80:8080"
  mftserver1:
    build: ./build
    image: test-mft-server-1
    container_name: test-mft-server-1-1
    hostname: test-mft-server-1-1
    networks:
      n1:
        aliases:
          - mftserver1
    depends_on:
      - "sql-server1"
    volumes:
      - mftserver1-temp:/tmp/
      # the following must match the Dokerfile folders, otherwise permissions on FS will not work
      - mftserver1-install-home:/app/sag/1005/mftServerTest1/
      - mftserver1-sum-home:/app/sag/sumv11/
      - mftserver1-runs:/app/audit/
      - ./scripts/:/mnt/scripts/
      # These must be provided, they are prerequisites
      - ${H_MFTSERVER_LICENSE_FILE}:/tmp/MFT_Server_license.xml
      - ${H_IS_LICENSE_FILE}:/tmp/IS_license.xml
      #- ${H_SUIF_FIXES_IMAGE_FILE}:/tmp/fixes.zip
      - ${H_SUIF_DBC4AT_INSTALL_IMAGE_FILE}:/tmp/dbc4at.product.image.zip
      - ${H_SUIF_AT_INSTALL_IMAGE_FILE}:/tmp/at.product.image.zip
      #- ${H_SUIF_PRODUCTS_IMAGE_FILE}:/tmp/products.zip
      - ${H_SUIF_DBC4AT_PATCH_FIXES_IMAGE_FILE}:/tmp/dbc4at.fixes.image.zip
      - ${H_SUIF_AT_PATCH_FIXES_IMAGE_FILE}:/tmp/at.fixes.image.zip
      - ${H_SUIF_SUM_BOOTSTRAP_BIN}:/tmp/sum-bootstrap.bin
      - ${H_SUIF_INSTALLER_BIN}:/tmp/installer.bin
      # SUIF provided - this exact branch
      - ../../../../:/mnt/SUIF_HOME/
    environment:
      # commonFunctions
      - SUIF_DEBUG_ON=1
      # this test runs offline
      - SUIF_ONLINE_MODE=0
      - SUIF_HOME=/mnt/SUIF_HOME
      - SUIF_AUDIT_BASE_DIR=/app/audit
      # providing only the must haves + install dir
      # setupFunctions
      - SUIF_INSTALL_INSTALLER_BIN=/tmp/installer.bin
      - SUIF_INSTALL_INSTALL_DIR=/app/sag/1005/mftServerTest1
      #- SUIF_INSTALL_IMAGE_FILE=/tmp/products.zip
      - SUIF_DBC4AT_INSTALL_IMAGE_FILE=/tmp/dbc4at.product.image.zip
      - SUIF_AT_INSTALL_IMAGE_FILE=/tmp/at.product.image.zip
      - SUIF_PATCH_SUM_BOOTSTRAP_BIN=/tmp/sum-bootstrap.bin
      #- SUIF_PATCH_FIXES_IMAGE_FILE=/tmp/fixes.zip
      - SUIF_DBC4AT_PATCH_FIXES_IMAGE_FILE=/tmp/dbc4at.fixes.image.zip
      - SUIF_AT_PATCH_FIXES_IMAGE_FILE=/tmp/at.fixes.image.zip
      - SUIF_SUM_HOME=/app/sag/sumv11/
      # setup template specifics
      - SUIF_SETUP_TEMPLATE_MFTSERVER_LICENSE_FILE=/tmp/MFT_Server_license.xml
      - SUIF_SETUP_TEMPLATE_IS_LICENSE_FILE=/tmp/IS_license.xml
      # database related
      - SUIF_SQLSERVER_HOSTNAME=sql-server1
      - SUIF_SQLSERVER_DATABASE_NAME=${H_SQLSERVER_DB_NAME}
      - SUIF_SQLSERVER_USER_NAME=${H_SQLSERVER_DB_USER}
      - SUIF_SQLSERVER_PASSWORD=${H_SQLSERVER_DB_PASSWORD}
      - SUIF_SQLSERVER_SA_PASSWORD=${H_SQLSERVER_SA_PASSWORD}
    ports:
      - "${H_SUIF_PORT_PREFIX}20:9240"
      - "${H_SUIF_PORT_PREFIX}55:5555"
      - "${H_SUIF_PORT_PREFIX}85:8500"
      - "${H_SUIF_PORT_PREFIX}91:9102"
    entrypoint: /mnt/scripts/containerEntrypoint.sh
