version: "3.5"

volumes:
  intg1-install-home: {}
  intg1-sum-home: {}
  intg1-runs: {}
  intg1-archives: {}
  intg1-config: {}
  intg1-data: {}
  intg1-logs: {}
  intg1-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  intg1:
    build: ./build
    image: test-intg-1
    container_name: test-intg-1-1
    hostname: test-intg-1-1
    ulimits:
      nproc: 4096
      nofile: 65536
    volumes:
      - intg1-temp:/tmp/
      # the following must match the Dokerfile folders, otherwise permissions on FS will not work
      - intg1-install-home:/app/sag/1005/IntgTest1/
      - intg1-sum-home:/app/sag/sumv11/
      - intg1-runs:/app/audit/
      - ./scripts/:/mnt/scripts/
      # These must be provided, they are prerequisites
      - ${H_INTG_LICENSE_FILE}:/tmp/IntegrationServer_license.xml
      - ${H_SUIF_FIXES_IMAGE_FILE}:/tmp/fixes.zip
      - ${H_SUIF_PRODUCTS_IMAGE_FILE}:/tmp/products.zip
      - ${H_SUIF_SUM_BOOTSTRAP_BIN}:/tmp/sum-bootstrap.bin
      - ${H_SUIF_INSTALLER_BIN}:/tmp/installer.bin
      - ../../../../:/mnt/SUIF_HOME/
    environment:
      # we declare SUIF_HOME because we mount it here
      - SUIF_HOME=/mnt/SUIF_HOME
      # we declare SUIF_AUDIT_BASE_DIR because we mount it here
      - SUIF_AUDIT_BASE_DIR=/app/audit
      # setupFunctions prerequisites map, declared here because provided by host
      - SUIF_INSTALL_INSTALLER_BIN=/tmp/installer.bin
      - SUIF_INSTALL_IMAGE_FILE=/tmp/products.zip
      - SUIF_PATCH_SUM_BOOTSTRAP_BIN=/tmp/sum-bootstrap.bin
      - SUIF_PATCH_FIXES_IMAGE_FILE=/tmp/fixes.zip
      # declare install dir and SUM dir because they are mounted here
      - SUIF_INSTALL_INSTALL_DIR=/app/sag/1005/IntgTest1
      - SUIF_SUM_HOME=/app/sag/sumv11/
      # setup template specifics - license provided by host
      - SUIF_SETUP_TEMPLATE_IS_LICENSE_FILE=/tmp/IntegrationServer_license.xml
    ports:
      - "${H_SUIF_PORT_PREFIX}55:5555"
    entrypoint: /mnt/scripts/containerEntrypoint.sh
