version: "3.5"

volumes:
  runs: {}
  containers:
    driver: vfs
  temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  buildah-msr1011-type-1:
    build: 
      context: ./build
      args:
        - SRC_IMAGE
        - SUIF_AUDIT_BASE_DIR
        - SUIF_INSTALL_INSTALL_DIR
        - SUIF_LOCAL_SCRIPTS_HOME
        - SUIF_SAG_USER_NAME
        - SUIF_SUM_HOME
    security_opt:
      - seccomp:unconfined
    image: buildah-msr1011-type-1
    container_name: buildah-msr1011-type-1-1
    hostname: buildah-msr1011-type-1-1
    volumes:
      - temp:/tmp/
      # the following must match the Dokerfile folders, otherwise permissions on FS will not work
      #- buildah-msr1011-type-1-install-home:${SUIF_INSTALL_INSTALL_DIR}/
      - runs:${SUIF_AUDIT_BASE_DIR}/
      - ./scripts/:${SUIF_LOCAL_SCRIPTS_HOME}/
      - ../../../../../:${SUIF_HOME}/
      - containers:/var/lib/containers
      # These must be provided, they are prerequisites
      - ${H_MSR_LICENSE_FILE}:${SUIF_SETUP_TEMPLATE_MSR_LICENSE_FILE}
      - ${H_SUIF_INSTALL_IMAGE_FILE}:${SUIF_INSTALL_IMAGE_FILE}
      - ${H_SUIF_INSTALL_INSTALLER_BIN}:${SUIF_INSTALL_INSTALLER_BIN}
      - ${H_SUIF_PATCH_FIXES_IMAGE_FILE}:${SUIF_PATCH_FIXES_IMAGE_FILE}
      - ${H_SUIF_PATCH_SUM_BOOSTSTRAP_BIN}:${SUIF_PATCH_SUM_BOOSTSTRAP_BIN}
    environment:
      - SUIF_AUDIT_BASE_DIR
      - SUIF_DEBUG_ON
      - SUIF_HOME
      - SUIF_INSTALL_IMAGE_FILE
      - SUIF_INSTALL_INSTALL_DIR
      - SUIF_INSTALL_INSTALLER_BIN
      - SUIF_INSTALL_TIME_ADMIN_PASSWORD
      - SUIF_ONLINE_MODE
      - SUIF_PATCH_AVAILABLE
      - SUIF_PATCH_FIXES_IMAGE_FILE
      - SUIF_PATCH_SUM_BOOSTSTRAP_BIN
      - SUIF_SETUP_TEMPLATE_MSR_LICENSE_FILE
      - SUIF_SUM_HOME
    entrypoint: ${SUIF_LOCAL_SCRIPTS_HOME}/containerEntrypoint.sh
