version: "3.5"

volumes:
  runs: {}
  temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  buildah-msr1011-type-1:
    build: 
      context: ./build
      args:
        - SUIF_INSTALL_INSTALL_DIR=${SUIF_INSTALL_INSTALL_DIR}
        - SUIF_AUDIT_BASE_DIR=${SUIF_AUDIT_BASE_DIR}
        - SUIF_INSTALL_INSTALLER_BIN=${SUIF_INSTALL_INSTALLER_BIN}
        - SUIF_INSTALL_IMAGE_FILE=${SUIF_INSTALL_IMAGE_FILE}
        - SUIF_SAG_USER_NAME=${SUIF_SAG_USER_NAME}
        - SUIF_LOCAL_SCRIPTS_HOME=${SUIF_LOCAL_SCRIPTS_HOME}
    image: buildah-msr1011-type-1
    container_name: buildah-msr1011-type-1-1
    hostname: buildah-msr1011-type-1-1
    volumes:
      - temp:/tmp/
      # the following must match the Dokerfile folders, otherwise permissions on FS will not work
      #- buildah-msr1011-type-1-install-home:${SUIF_INSTALL_INSTALL_DIR}/
      - runs:${SUIF_AUDIT_BASE_DIR}/
      - ./scripts/:${SUIF_LOCAL_SCRIPTS_HOME}/
      # These must be provided, they are prerequisites
      - ${H_MSR_LICENSE_FILE}:${SUIF_SETUP_TEMPLATE_MSR_LICENSE_FILE}
      - ${H_SUIF_PRODUCTS_IMAGE_FILE}:${SUIF_INSTALL_IMAGE_FILE}
      - ${H_SUIF_INSTALLER_BIN}:${SUIF_INSTALL_INSTALLER_BIN}
      - ${H_SUIF_SUM_BOOTSTRAP_BIN}:${SUIF_SUM_BOOTSTRAP_BIN}
      - ${H_SUIF_FIXES_IMAGE_FILE}:${SUIF_FIXES_IMAGE_FILE}
      - ../../../../../:${SUIF_HOME}/
    environment:
      - SUIF_AUDIT_BASE_DIR
      - SUIF_DEBUG_ON
      - SUIF_FIXES_IMAGE_FILE
      - SUIF_HOME
      - SUIF_INSTALL_IMAGE_FILE
      - SUIF_INSTALL_INSTALL_DIR
      - SUIF_INSTALL_INSTALLER_BIN
      - SUIF_INSTALL_TIME_ADMIN_PASSWORD
      - SUIF_LOCAL_SCRIPTS_HOME
      - SUIF_ONLINE_MODE
      - SUIF_PATCH_AVAILABLE
      - SUIF_SETUP_TEMPLATE_MSR_LICENSE_FILE
      - SUIF_SUM_BOOTSTRAP_BIN
    entrypoint: ${SUIF_LOCAL_SCRIPTS_HOME}/containerEntrypoint.sh
