version: "1.0"

volumes:
  mftserver1-install-home: {}
  mftserver1-sum-home: {}
  mftserver1-runs: {}
  mftserver1-archives: {}
  mftserver1-config: {}
  mftserver1-data: {}
  mftserver1-logs: {}
  mftserver1-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  mftserver1:
    build: ./build
    image: test-mft-server-1
    container_name: test-mft-server-1-1
    hostname: test-mft-server-1-1
    ulimits:
      nproc: 4096
      nofile: 65536
    volumes:
      - mftserver1-temp:/tmp/
      # the following must match the Dokerfile folders, otherwise permissions on FS will not work
      - mftserver1-install-home:/app/sag/1005/mftServerTest1/
      - mftserver1-sum-home:/app/sag/sumv11/
      - mftserver1-runs:/app/audit/
      # volumes for the changing folders for ES ...
      #- mftserver1-archives:/app/sag/1005/ApiGwTest1/InternalDataStore/archives/
      #- mftserver1-config:/app/sag/1005/ApiGwTest1/InternalDataStore/config/
      #- mftserver1-data:/app/sag/1005/ApiGwTest1/InternalDataStore/data/
      #- mftserver1-logs:/app/sag/1005/ApiGwTest1/InternalDataStore/logs/
      - ./scripts/:/mnt/scripts/
      # These must be provided, they are prerequisites
      - ${H_MFTGW_GW_LICENSE_FILE}:/tmp/MFT_Server_license.xml
      - ${H_SUIF_FIXES_IMAGE_FILE}:/tmp/fixes.zip
      - ${H_SUIF_PRODUCTS_IMAGE_FILE}:/tmp/products.zip
      - ${H_SUIF_SUM_BOOTSTRAP_BIN}:/tmp/sum-bootstrap.bin
      - ${H_SUIF_INSTALLER_BIN}:/tmp/installer.bin
      - ../../../../:/mnt/SUIF_HOME/
    environment:
      # commonFunctions
      - SUIF_DEBUG_ON=1
      # this test runs online
      - SUIF_ONLINE_MODE=0
      - SUIF_HOME=/mnt/SUIF_HOME
      - SUIF_AUDIT_BASE_DIR=/app/audit
      # providing only the must haves + install dir
      # setupFunctions
      - SUIF_INSTALL_INSTALLER_BIN=/tmp/installer.bin
      - SUIF_INSTALL_INSTALL_DIR=/app/sag/1005/mftServerTest1
      - SUIF_INSTALL_IMAGE_FILE=/tmp/products.zip
      - SUIF_PATCH_SUM_BOOSTSTRAP_BIN=/tmp/sum-bootstrap.bin
      - SUIF_PATCH_FIXES_IMAGE_FILE=/tmp/fixes.zip
      - SUIF_SUM_HOME=/app/sag/sumv11/
      # setup template specifics
      - SUIF_SETUP_TEMPLATE_MFTGW_LICENSE_FILE=/tmp/MFT_Server_license.xml
    ports:
      - "${H_SUIF_PORT_PREFIX}20:9240"
      #- "${H_SUIF_PORT_PREFIX}73:9073"
      #- "${H_SUIF_PORT_PREFIX}72:9072"
      - "${H_SUIF_PORT_PREFIX}55:5555"
      - "${H_SUIF_PORT_PREFIX}85:8500"
    entrypoint: /mnt/scripts/containerEntrypoint.sh
