version: '3.9'

services:
  d:
    # downloader service
    image: alpine
    volumes:
      - ../../../../:/mnt/SUIF
      - ./scripts/:/mnt/scripts
      - ./local/:/mnt/local/
    environment:
      - SUIF_INSTALL_INSTALLER_BIN=/mnt/local/default-installer.bin
      - SUIF_PATCH_SUM_BOOTSTRAP_BIN=/mnt/local/default-sum-bootstrap.bin
    entrypoint: /mnt/scripts/entrypoint.sh

