version: "3.5"

volumes:
  #msr1011-lean-builder-type-1-install-home: {}
  # this time we WANT the installation to be ephemeral
  msr1011-lean-builder-type-1-runs: {}
  msr1011-lean-builder-type-1-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
services:
  msr1011-lean-builder-type-1:
    build: 
      context: ./build
      args:
        - SUIF_INSTALL_INSTALL_DIR=${SUIF_INSTALL_INSTALL_DIR}
        - SUIF_AUDIT_BASE_DIR=${SUIF_AUDIT_BASE_DIR}
        - SUIF_INSTALL_INSTALLER_BIN=${SUIF_INSTALL_INSTALLER_BIN}
        - SUIF_INSTALL_IMAGE_FILE=${SUIF_INSTALL_IMAGE_FILE}
        - SUIF_SAG_USER_NAME=${SUIF_SAG_USER_NAME}
        - SUIF_LOCAL_SCRIPTS_HOME=${SUIF_LOCAL_SCRIPTS_HOME}
    image: msr1011-lean-builder-type-1
    container_name: msr1011-lean-builder-type-1-1
    hostname: msr1011-lean-builder-type-1-1
    volumes:
      - msr1011-lean-builder-type-1-temp:/tmp/
      # the following must match the Dokerfile folders, otherwise permissions on FS will not work
      #- msr1011-lean-builder-type-1-install-home:${SUIF_INSTALL_INSTALL_DIR}/
      - msr1011-lean-builder-type-1-runs:${SUIF_AUDIT_BASE_DIR}/
      - ./scripts/:${SUIF_LOCAL_SCRIPTS_HOME}/
      # These must be provided, they are prerequisites
      - ${H_MSR_LICENSE_FILE}:${SUIF_SETUP_TEMPLATE_MSR_LICENSE_FILE}
      - ${H_SUIF_PRODUCTS_IMAGE_FILE}:${SUIF_INSTALL_IMAGE_FILE}
      - ${H_SUIF_INSTALLER_BIN}:${SUIF_INSTALL_INSTALLER_BIN}
      - ../../../../:${SUIF_HOME}/
      # we need access to docker because we are building...
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SUIF_HOME
      - SUIF_AUDIT_BASE_DIR
      - SUIF_INSTALL_INSTALLER_BIN
      - SUIF_INSTALL_IMAGE_FILE
      - SUIF_PATCH_AVAILABLE
      - SUIF_INSTALL_INSTALL_DIR
      - SUIF_SETUP_TEMPLATE_MSR_LICENSE_FILE
      - SUIF_INSTALL_TIME_ADMIN_PASSWORD
      - SUIF_LOCAL_SCRIPTS_HOME
      - SUIF_ONLINE_MODE
      - SUIF_DEBUG_ON
    entrypoint: ${SUIF_LOCAL_SCRIPTS_HOME}/containerEntrypoint.sh
